Added SSL support
saghul/CallRoulette pull request #4
Opened 2017-01-13 14:35 UTC by carlitoselmago

fix for "getusermedia no longer works on insecure origins"

2017-01-13 14:48 UTC, saghul requested changes
Thanks for doing this!  Left some comments.

2017-01-13 14:48 UTC, saghul commented on app.py
> +port=5000
please don't do this.  Either make it properly configurable or leave it as it was.

2017-01-13 14:48 UTC, saghul commented on app.py
> +
unneeded change

2017-01-13 14:48 UTC, saghul commented on app.py
> +
unneeded change

2017-01-13 14:48 UTC, saghul commented on app.py
> +        ws = web.WebSocketResponse(protocols=('callroulette-v2'))
it's a tuple, the comma is relevant.

2017-01-13 14:48 UTC, saghul commented on app.py
> +
unneeded change

2017-01-13 14:48 UTC, saghul commented on app.py
> +    server = yield from loop.create_server(handler, '0.0.0.0', port,ssl=sslcontext)
style: space after comma

2017-01-13 14:48 UTC, saghul commented on static/js/app.js
> -
please leave this file unformatted, I don't like unrelated style changes. Except the wss change, of course :-)

2017-01-13 15:16 UTC, carlitoselmago commented
I reverted some of the non related format changes etc. Now it's just the strict fix, nothing else.

2017-01-14 18:07 UTC, merged

2017-01-14 18:07 UTC, saghul commented
Great work, thanks!